application: plaudible
version: 1
runtime: python
api_version: 1

handlers:
- url: /feed.*
  script: FeedHandler.py
  
- url: /article.*
  script: ArticleHandler.py

- url: /addsource.*
  script: addnewssource.py

builtins:
- remote_api: on